# Do not modify this file!  It was generated by ‘nixos-generate-confignix-shell -p libva-utils --run vainfo’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ pkgs, config, lib, modulesPath, unstablePkgs, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  hardware = {
    enableAllFirmware = true;
    acpilight.enable = true;

    ## Result is the same with any of the 3 platforms.
    ipu6 = {
      enable = true;
      platform = "ipu6epmtl";
      # platform = "ipu6ep";
      # platform = "ipu6";
    };

    bluetooth = {
      enable = true; # enables support for Bluetooth
      powerOnBoot = true; # powers up the default Bluetooth controller on boot
    };

    graphics = {
      enable = true;
      # package = unstablePkgs.mesa.drivers;
      package = pkgs.mesa.drivers;
      # driSupport = true;
      # package32 = unstablePkgs.pkgsi686Linux.mesa.drivers;
      package32 = pkgs.pkgsi686Linux.mesa.drivers;
      enable32Bit = true;
      # extraPackages = with unstablePkgs; [
      extraPackages = with pkgs; [
        intel-media-driver # LIBVA_DRIVER_NAME=iHD
        vaapiVdpau
        libvdpau-va-gl
        intel-compute-runtime # 8th gen +
      ];
    };

    enableRedistributableFirmware = true;
    cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  };


  boot = {
    loader = {
      systemd-boot.enable = true;
      efi.canTouchEfiVariables = true;
    };

    initrd = {
      luks.devices."luks-298baab0-a3a5-4047-8b67-f029dcb5b71d".device = "/dev/disk/by-uuid/298baab0-a3a5-4047-8b67-f029dcb5b71d";
      luks.devices."luks-36243564-61b5-4a6d-9d3b-891a1e6ff056".device = "/dev/disk/by-uuid/36243564-61b5-4a6d-9d3b-891a1e6ff056";

      availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" ];
      kernelModules = [ "xe" ];
    };

    # kernelPackages = pkgs.linuxPackages_latest;
    # kernelPackages = pkgs.linuxKernel.packages.linux_6_9;

    kernelPackages = pkgs.linuxPackages_latest.extend ( self: super: {
      ipu6-drivers = super.ipu6-drivers.overrideAttrs (
          final: previous: rec {
            src = builtins.fetchGit {
              url = "https://github.com/intel/ipu6-drivers.git";
              ref = "master";
              rev = "b4ba63df5922150ec14ef7f202b3589896e0301a";
            };
            patches = [
              "${src}/patches/0001-v6.10-IPU6-headers-used-by-PSYS.patch"
            ] ;
          }
      );
    } );


    kernelModules = [ "kvm-intel" ];
    extraModulePackages = [ ];

  };


  fileSystems."/" =
    { device = "/dev/disk/by-uuid/a1132835-1edf-451b-8157-d21b997e6e33";
      fsType = "ext4";
    };


  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/D8B0-A3CA";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices =
    [ 
      { device = "/dev/disk/by-uuid/066388a4-bd87-402b-8d42-6195316fe5e7"; }
    ];

  networking.hostName = "upsetter"; # Define your hostname.

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  services.hardware.bolt.enable = true;

}
